name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.17
          - 1.16 # runtime needed
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: setup
        run: |
          # https://github.com/golangci/golangci-lint/releases/
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

      - name: test
        run: |
          make lint
          make test

      - name: build
        run: |
          make build
